name = "movecar"
main = "movecar.js"
compatibility_date = "2025-11-04"
keep_vars = true

# 触发构建1
[[kv_namespaces]]
binding = "MOVE_CAR_STATUS"    # 
id = "90b7287275db449e9cc5f366d2d92204" # 替换为你的实际 KV ID
